package com.porasl.notification.email;

public enum EmailEnum {
  ACCOUNT_ACTIVATION,
  FORGOT_PASSWORD,
  ACCOUNT_CREATED,
  ACCOUNT_DELETED,
  INVITED_TO_INRIK,
  INVITED_TO_GROUP,
  POST_COMMENTED,
  CHANNEL_COMMENTED
}
